all:
    hosts:
        prod:
            ansible_host: 10.0.0.11
            ansible_port: 22
            ansible_user: vagrant
            ansible_ssh_extra_args: "-o ForwardAgent=yes -o IdentitiesOnly=yes"
            ansible_ssh_private_key_file: "/home/vrepetskiy/.ssh/id_rsa"
            ansible_python_interpreter: /usr/bin/python3
        preprod:
            ansible_host: 10.0.0.12
            ansible_port: 22
            ansible_user: vagrant
            ansible_ssh_extra_args: "-o ForwardAgent=yes -o IdentitiesOnly=yes"
            ansible_ssh_private_key_file: "/home/vrepetskiy/.ssh/id_rsa"
            ansible_python_interpreter: /usr/bin/python3
    children:
        webservers:
            hosts:
                preprod:
                prod:
